// AUTO-GENERATED by scripts/generate-content.mjs — do not edit by hand.
// Edit the files in content/ instead (or use the CMS at /admin), then
// re-run `npm run generate-content` (also runs automatically before
// dev/build).

import type { Content } from "./content.types";

export const content: Content = {
  "nav": {
    "brand": "AZADICHORDS",
    "tagline": "The Voice of Freedom",
    "links": [
      {
        "href": "/manifesto",
        "label": "Manifesto"
      },
      {
        "href": "/music",
        "label": "Music"
      },
      {
        "href": "/artists",
        "label": "Artists"
      },
      {
        "href": "/activity",
        "label": "Activity"
      },
      {
        "href": "/press",
        "label": "Press"
      },
      {
        "href": "/services",
        "label": "Services"
      },
      {
        "href": "/submissions",
        "label": "Submissions"
      },
      {
        "href": "/support",
        "label": "Support"
      },
      {
        "href": "/contact",
        "label": "Contact"
      }
    ]
  },
  "hero": {
    "eyebrow": "Independent Music Label — Paris",
    "title": "AZADICHORDS",
    "subhead": "An independent label for the voice that refuses to be silent.",
    "ctaPrimary": {
      "label": "Listen",
      "href": "/music"
    },
    "ctaSecondary": {
      "label": "The Manifesto",
      "href": "/manifesto"
    },
    "scrollHint": "(Scroll for more)",
    "promoBar": {
      "label": "The Record + The Room includes a ticket to our first live performance",
      "href": "/support"
    }
  },
  "manifesto": {
    "eyebrow": "Manifesto",
    "title": "A Label Built in Exile",
    "imageCaption": "portrait — Kamran Rasoolzadeh, Paris",
    "paragraphs": [
      "Azadichords is built from two words: Azadi — freedom — and chords. Here, the two become one.",
      "We are an independent label for voices that cannot, and will not, stay silent. For poetry and music that breaks through censorship, not with its permission.",
      "We don't release artists; we release a belief — that every voice, even in exile, even forced into silence, has the right to be heard.",
      "This label began with one voice. It was never meant to end with it.",
      "Azadichords began with a decision: that committed music and poetry deserve a label that stands fully behind it — not just behind a single song.",
      "Every album, every track, every poem is a step toward the day this label is home to many voices, not one."
    ],
    "closing": "Kamran Rasoolzadeh — poet, composer, and singer-songwriter — founded this label as its first artist. Not to remain the only one, but to be the first of many voices still to come.",
    "cta": {
      "label": "Meet the Artist →",
      "href": "/artists"
    }
  },
  "music": {
    "eyebrow": "Music",
    "title": "Music",
    "intro": "This label exists because of one record — Azadichords' debut release, forthcoming from its first artist, Kamran Rasoolzadeh.",
    "closing": "The label's first release — including official videos — arrives soon.",
    "comingSoonLabel": "Coming Soon",
    "tracksComingSoonLabel": "Tracks arriving soon.",
    "videoComingSoonLabel": "Music video arriving soon.",
    "demoComingSoonLabel": "Demo arriving soon.",
    "getReleaseLabel": "Get This Release",
    "getReleaseNote": "Stream everywhere once released — or get it now, plus a ticket to our first live show.",
    "getReleaseCtaLabel": "See how →"
  },
  "artistsPage": {
    "eyebrow": "Artists",
    "title": "Artists",
    "intro": "Every Azadichords artist is a voice that chose not to stay silent."
  },
  "artists": [
    {
      "slug": "kamran-rasoolzadeh",
      "name": "Kamran Rasoolzadeh",
      "role": "Poet, Composer, Singer-Songwriter",
      "badge": "Founding Artist",
      "imageCaption": "portrait — Kamran, close crop",
      "intro": "Kamran Rasoolzadeh writes, composes, and performs songs shaped by exile and return. His work has been banned, awarded, and — after years of silence — is beginning again.",
      "bio": "Kamran Rasoolzadeh is an Iranian poet, composer, and singer-songwriter. His poetry has topped bestseller lists in Iran for over a decade. In 2014, he composed and produced <em>CHESHMAT</em> for vocalist Mehrnoosh — an album that became one of the defining records of its generation, despite, and in part because of, the restrictions placed on the work. After years of censorship and repeated pressure from state authorities, he left Iran and settled in France, where he now lives and works. He founded Azadichords as its Founding Artist.",
      "cta": {
        "label": "Explore the Music →",
        "href": "/music"
      },
      "recognition": [
        {
          "award": "Iranian Film Festival San Francisco",
          "category": "Best Music Video — Freedom",
          "year": "2022"
        },
        {
          "award": "K-Music and Arts Film Festival, Seoul",
          "category": "Best Music Video — Freedom",
          "year": "2022"
        },
        {
          "award": "ZILANT International Film Festival",
          "category": "Best Music Video — Freedom",
          "year": "2022"
        },
        {
          "award": "Fajr Music Festival",
          "category": "Best Songwriting",
          "year": "2022"
        },
        {
          "award": "Baku Poetry Festival",
          "category": "Honorary Diploma",
          "year": "2015"
        }
      ]
    }
  ],
  "releases": [
    {
      "slug": "iran-e-jan",
      "title": "Iran-e Jan",
      "type": "album",
      "artist": "kamran-rasoolzadeh",
      "status": "upcoming",
      "releaseDate": "2026-09-16",
      "coverImageCaption": "Iran-e Jan — album art",
      "tagline": "The debut release from Azadichords — arriving September 16, 2026.",
      "description": "Iran-e Jan is Kamran Rasoolzadeh's debut release under Azadichords — eleven tracks written in the shadow of a country in mourning and the light of one that refuses to stay silent. Lead single \"Bang Bang\" premieres September 1; the full album follows on September 16 — the anniversary of Jina Mahsa Amini's death.",
      "demoAudioUrl": "",
      "videoUrl": "",
      "videoCaption": "",
      "tracks": [
        {
          "trackNumber": 1,
          "title": "Bang Bang",
          "duration": "",
          "previewUrl": ""
        },
        {
          "trackNumber": 2,
          "title": "1819",
          "duration": "",
          "previewUrl": ""
        }
      ],
      "streamingLinks": [],
      "supportTierLink": true,
      "purchaseNote": ""
    },
    {
      "slug": "cheshmat",
      "title": "CHESHMAT",
      "type": "album",
      "artist": "kamran-rasoolzadeh",
      "status": "out_now",
      "releaseDate": "2014",
      "coverImageCaption": "CHESHMAT — 2014 album art",
      "tagline": "The 2014 album that shaped a generation — and drew the attention that would later silence him.",
      "description": "Before Azadichords, Kamran composed and produced <em>CHESHMAT</em> (2014) for vocalist Mehrnoosh — a record that shaped a generation, and drew the attention that would eventually silence him. His music video <em>Freedom</em> — a meditation on liberation as the foundation of a free society — later won Best Music Video at festivals in San Francisco, Seoul, and Kazan.",
      "demoAudioUrl": "",
      "videoUrl": "",
      "videoCaption": "",
      "tracks": [],
      "streamingLinks": [],
      "supportTierLink": false,
      "purchaseNote": ""
    }
  ],
  "activityPage": {
    "eyebrow": "Activity",
    "title": "Activity",
    "intro": "A running record of where Azadichords has been — performances, releases, and the milestones along the way.",
    "emptyStateNote": "Azadichords is early. This record starts with the first release and the first show — both are still ahead."
  },
  "activity": [],
  "press": {
    "eyebrow": "Press",
    "title": "Press",
    "paragraphs": [
      "Press materials and interviews will appear here as they're published.",
      "For press inquiries, use the contact form."
    ]
  },
  "services": {
    "eyebrow": "Services",
    "title": "What the Label Offers",
    "intro": "Beyond release, Azadichords works alongside the artists it houses at every stage a record needs before it reaches an audience.",
    "items": [
      {
        "title": "Production & Mixing",
        "description": "Studio time, arrangement, and audio engineering support, from first draft to final master."
      },
      {
        "title": "Distribution",
        "description": "Placing the work on every major platform, worldwide, under the artist's own name."
      },
      {
        "title": "Visual Identity",
        "description": "Album art, music videos, and the visual language that carries a record beyond its audio."
      },
      {
        "title": "Live Performance",
        "description": "From a first show to a touring itinerary — the logistics behind bringing a record to a stage."
      },
      {
        "title": "Licensing & Publishing",
        "description": "Protecting the work and placing it commercially, on terms the artist understands and agrees to."
      }
    ],
    "cta": {
      "label": "Working on something that belongs here? Get in Touch →",
      "href": "/contact"
    }
  },
  "submissions": {
    "eyebrow": "Submissions",
    "title": "For the Next Voice",
    "intro": "If your voice is something that can't stay silent, we want to hear it. Azadichords is looking for artists whose music and poetry come from a belief, not just a genre. Send us your work.",
    "guidelines": [
      "2–3 tracks, in their current form — polished or not.",
      "A few sentences about the work and the story behind it.",
      "No press kit, no pitch deck. Just the music."
    ],
    "note": "Submissions are reviewed as time allows. Not every submission gets a reply — but every one gets heard.",
    "cta": {
      "label": "Submit Your Work →",
      "href": "/contact"
    }
  },
  "support": {
    "eyebrow": "Support",
    "title": "Support the Project",
    "intro": [
      "Azadichords is fully independent — no committee, no gatekeeper, no institutional funding. That independence is made possible directly by the people who choose to support it.",
      "Every contribution on this page goes directly toward bringing this music to a stage — production, travel, and the first live performances across Europe."
    ],
    "tiers": [
      {
        "name": "Tier 1",
        "title": "The Record",
        "description": "High-resolution digital album (FLAC + lossless) plus a digital lyric booklet with the story behind each song.",
        "note": ""
      },
      {
        "name": "Tier 2",
        "title": "The Record + The Room",
        "description": "Everything in Tier 1, plus a ticket (or priority access) to the first live performance.",
        "note": ""
      },
      {
        "name": "Tier 3",
        "title": "Founding Supporter",
        "description": "Everything in Tier 2, plus recognition as an early supporter of independent art.",
        "note": "By default, founding supporters are listed anonymously (\"A Founding Supporter\"). If you would prefer your name included instead, you can opt in during checkout — entirely your choice."
      }
    ],
    "cta": {
      "label": "Get in Touch",
      "href": "/contact"
    },
    "transparency": "All proceeds go directly to production and live performance costs. No intermediary, no committee."
  },
  "contact": {
    "eyebrow": "Contact",
    "title": "Get in Touch",
    "subhead": "For music, press, or performance inquiries.",
    "fields": {
      "name": "Name",
      "email": "Email",
      "subject": "Subject",
      "category": "Category"
    },
    "categories": [
      "General",
      "Submission",
      "Press",
      "Booking",
      "Licensing"
    ],
    "submit": "Send"
  },
  "footer": {
    "copyright": "AZADICHORDS © 2026 — Paris",
    "social": [
      {
        "label": "Instagram",
        "href": "#"
      },
      {
        "label": "YouTube",
        "href": "#"
      },
      {
        "label": "Spotify",
        "href": "#"
      },
      {
        "label": "Telegram",
        "href": "#"
      }
    ],
    "disclaimer": "Azadichords is an independent label with no affiliation to any political party, movement, or government."
  }
};
