// AUTO-GENERATED by scripts/generate-content.mjs — do not edit by hand.
// Edit the files in content/ instead (or use the CMS at /admin), then
// re-run `npm run generate-content` (also runs automatically before
// dev/build).

import type { Content } from "./content.types";

export const content: Content = {
  "nav": {
    "brand": "AZADICHORDS",
    "links": [
      {
        "href": "/manifesto",
        "label": "Manifesto"
      },
      {
        "href": "/music",
        "label": "Music"
      },
      {
        "href": "/artists",
        "label": "Artists"
      },
      {
        "href": "/press",
        "label": "Press"
      },
      {
        "href": "/support",
        "label": "Support"
      },
      {
        "href": "/contact",
        "label": "Contact"
      }
    ]
  },
  "hero": {
    "eyebrow": "Independent Music Label — Paris",
    "title": "AZADICHORDS",
    "subhead": "An independent label for the voice that refuses to be silent.",
    "ctaPrimary": {
      "label": "Listen",
      "href": "/music"
    },
    "ctaSecondary": {
      "label": "Our Story",
      "href": "/manifesto"
    },
    "scrollHint": "(Scroll for more)"
  },
  "manifesto": {
    "eyebrow": "Manifesto",
    "title": "A Label Built in Exile",
    "imageCaption": "portrait — Kamran Rasoolzadeh, Paris",
    "paragraphs": [
      "Azadichords began with an album — a record that needed a home beyond permission: no committee, no censor, no government approval required. So one was built, in Paris, in 2026.",
      "We believe music is one of the last languages that cannot be fully policed. A melody crosses borders that people cannot. A lyric survives censorship that speeches do not.",
      "Azadichords exists for that music — songs written by those who were told to stop writing, sung by voices that were told to go quiet. We are independent by choice, not necessity — no committee decides what we release, and no permission is required for what we say.",
      "This is not a protest label. It is a human one. Some of what we release speaks directly to a moment in history. Most of it speaks, as music always has, to love, loss, and the ordinary weight of being alive."
    ],
    "closing": "That first album belongs to Kamran Rasoolzadeh — poet, composer, and the label's first artist.",
    "cta": {
      "label": "Meet the Artist →",
      "href": "/artists/kamran-rasoolzadeh"
    }
  },
  "music": {
    "eyebrow": "Music",
    "title": "Music",
    "intro": "This label exists because of one record — Azadichords' debut release, forthcoming from its first artist, Kamran Rasoolzadeh.",
    "closing": "The label's first release — including official videos — arrives soon.",
    "comingSoonLabel": "Coming Soon",
    "tracksComingSoonLabel": "Tracks arriving soon.",
    "videoComingSoonLabel": "Music video arriving soon."
  },
  "artistsPage": {
    "eyebrow": "Artists",
    "title": "Artists",
    "intro": "Azadichords is built to grow beyond a single voice. It begins with one artist — more will join as the label expands.",
    "viewProfile": "View Profile →"
  },
  "artists": [
    {
      "slug": "kamran-rasoolzadeh",
      "name": "Kamran Rasoolzadeh",
      "role": "Poet, Composer, Singer-Songwriter",
      "imageCaption": "portrait — Kamran, close crop",
      "intro": "Kamran Rasoolzadeh writes, composes, and performs songs shaped by exile and return. His work has been banned, awarded, and — after years of silence — is beginning again.",
      "bio": "Kamran Rasoolzadeh is an Iranian poet, composer, and singer-songwriter. His 2014 album <em>CHESHMAT</em> became one of the defining records of its generation, despite — and in part because of — the restrictions placed on his work. After years of censorship and repeated pressure from state authorities, he left Iran and settled in France, where Azadichords was born.",
      "cta": {
        "label": "Explore the Music →",
        "href": "/music"
      }
    }
  ],
  "albums": [
    {
      "slug": "cheshmat",
      "title": "CHESHMAT",
      "artist": "kamran-rasoolzadeh",
      "year": 2014,
      "status": "released",
      "coverImageCaption": "CHESHMAT — 2014 album art",
      "blurb": "Before founding the label, Kamran released <em>CHESHMAT</em> (2014) — the record that shaped a generation, and drew the attention that would eventually silence him.",
      "tracks": [],
      "musicVideoUrl": "",
      "musicVideoCaption": "",
      "externalListen": {
        "label": "Listen to CHESHMAT →",
        "href": "#"
      }
    }
  ],
  "press": {
    "eyebrow": "Press",
    "title": "Press",
    "paragraphs": [
      "Press materials and interviews will appear here as they're published.",
      "For press inquiries, use the contact form."
    ]
  },
  "support": {
    "eyebrow": "Support",
    "title": "Support the Project",
    "intro": [
      "Azadichords is fully independent — no committee, no gatekeeper, no institutional funding. That independence is made possible directly by the people who choose to support it.",
      "Every contribution on this page goes directly toward bringing this music to a stage — production, travel, and the first live performances across Europe."
    ],
    "tiers": [
      {
        "name": "Tier 1",
        "title": "The Record",
        "description": "High-resolution digital album (FLAC + lossless) plus a digital lyric booklet with the story behind each song.",
        "note": ""
      },
      {
        "name": "Tier 2",
        "title": "The Record + The Room",
        "description": "Everything in Tier 1, plus a ticket (or priority access) to the first live performance.",
        "note": ""
      },
      {
        "name": "Tier 3",
        "title": "Founding Supporter",
        "description": "Everything in Tier 2, plus recognition as an early supporter of independent art.",
        "note": "By default, founding supporters are listed anonymously (\"A Founding Supporter\"). If you would prefer your name included instead, you can opt in during checkout — entirely your choice."
      }
    ],
    "cta": {
      "label": "Get in Touch",
      "href": "/contact"
    },
    "transparency": "All proceeds go directly to production and live performance costs. No intermediary, no committee."
  },
  "contact": {
    "eyebrow": "Contact",
    "title": "Get in Touch",
    "subhead": "For music, press, or performance inquiries.",
    "fields": {
      "name": "Name",
      "email": "Email",
      "subject": "Subject",
      "category": "Category"
    },
    "categories": [
      "General",
      "Press",
      "Booking",
      "Licensing"
    ],
    "submit": "Send"
  },
  "footer": {
    "copyright": "AZADICHORDS © 2026 — Paris",
    "social": [
      {
        "label": "Instagram",
        "href": "#"
      },
      {
        "label": "YouTube",
        "href": "#"
      },
      {
        "label": "Spotify",
        "href": "#"
      },
      {
        "label": "Telegram",
        "href": "#"
      }
    ],
    "disclaimer": "Azadichords is an independent label with no affiliation to any political party, movement, or government."
  }
};
