// AUTO-GENERATED by scripts/generate-content.mjs — do not edit by hand.
// Edit the files in content/ instead (or use the CMS at /admin), then
// re-run `npm run generate-content` (also runs automatically before
// dev/build).

import type { Content, Locale } from "./content.types";

export const content: Record<Locale, Content> = {
  "en": {
    "nav": {
      "brand": "AZADICHORDS",
      "tagline": "Home for Free Voices",
      "links": [
        {
          "href": "/manifesto",
          "label": "Manifesto"
        },
        {
          "href": "/music",
          "label": "Music"
        },
        {
          "href": "/festival",
          "label": "Festival"
        },
        {
          "href": "/artists",
          "label": "Artists"
        },
        {
          "href": "/submissions",
          "label": "Submissions"
        },
        {
          "href": "/support",
          "label": "Support"
        },
        {
          "href": "/contact",
          "label": "Contact"
        }
      ]
    },
    "hero": {
      "eyebrow": "Independent Label & Festival — Paris",
      "title": "AZADICHORDS",
      "subhead": "A home for free voices — a label that releases them, a festival that finds them.",
      "ctaPrimary": {
        "label": "Listen",
        "href": "/music"
      },
      "ctaSecondary": {
        "label": "The Festival",
        "href": "/festival"
      },
      "scrollHint": "(Scroll for more)",
      "promoBar": {
        "label": "Azadichords Festival · January 8–9, 2027 · Free entry for artists",
        "href": "/festival"
      }
    },
    "manifesto": {
      "eyebrow": "Manifesto",
      "title": "A Label Built in Exile",
      "imageCaption": "Azadichords — Requiem for the Eternal Names, album art",
      "paragraphs": [
        "Azadichords is built from two words: Azadi — freedom — and chords. Here, the two become one.",
        "We are an independent label for voices that cannot, and will not, stay silent. For poetry and music that breaks through censorship, not with its permission.",
        "We don't release artists; we release a belief — that every voice, even in exile, even forced into silence, has the right to be heard.",
        "This label began with one voice. It was never meant to end with it.",
        "Azadichords began with a decision: that committed music and poetry deserve a label that stands fully behind it — not just behind a single song.",
        "Every album, every track, every poem is a step toward the day this label is home to many voices, not one.",
        "That is why the label has a second door: a festival. Each year it gathers voices that have not yet been heard, and the label carries the chosen ones further."
      ],
      "closing": "Kamran Rasoolzadeh — poet, composer, and singer-songwriter — founded this label as its first artist. Not to remain the only one, but to be the first of many voices still to come.",
      "cta": {
        "label": "Meet the Artist →",
        "href": "/artists"
      }
    },
    "music": {
      "eyebrow": "Music",
      "title": "Music",
      "intro": "The Azadichords catalog begins with a requiem — and continues with the voices our festival brings to light.",
      "closing": "Next on the label: a compilation of the selected artists from Azadichords Festival 2027.",
      "comingSoonLabel": "Coming Soon",
      "tracksComingSoonLabel": "Tracks arriving soon.",
      "videoComingSoonLabel": "The first music video arrives before the album.",
      "demoComingSoonLabel": "First listen arriving soon.",
      "listenLabel": "Listen",
      "tracksLabel": "Tracks",
      "videoLabel": "Video",
      "typeLabels": {
        "album": "Album",
        "single": "Single",
        "ep": "EP"
      },
      "getReleaseLabel": "Get This Release",
      "getReleaseNote": "Stream it everywhere once released — or own it directly from the artist.",
      "getReleaseCtaLabel": "See how →"
    },
    "artistsPage": {
      "eyebrow": "Artists",
      "title": "Artists",
      "intro": "Every Azadichords artist is a voice that chose not to stay silent."
    },
    "artists": [
      {
        "slug": "kamran-rasoolzadeh",
        "name": "Kamran Rasoolzadeh",
        "role": "Poet, Composer, Singer-Songwriter",
        "badge": "Founding Artist",
        "imageCaption": "portrait — Kamran, close crop",
        "intro": "Kamran Rasoolzadeh writes, composes, and performs songs shaped by exile and return. His work has been banned, awarded, and — after years of silence — is beginning again.",
        "bio": "Kamran Rasoolzadeh is an Iranian poet, composer, and singer-songwriter. His poetry has topped bestseller lists in Iran for over a decade. In 2014, he composed and produced <em>CHESHMAT</em> for vocalist Mehrnoosh — an album that became one of the defining records of its generation, despite, and in part because of, the restrictions placed on the work. After years of censorship and repeated pressure from state authorities, he left Iran and settled in France, where he now lives and works. He founded Azadichords as its Founding Artist.",
        "cta": {
          "label": "Explore the Music →",
          "href": "/music"
        },
        "recognition": [
          {
            "award": "Iranian Film Festival San Francisco",
            "category": "Best Music Video — Freedom",
            "year": "2022"
          },
          {
            "award": "K-Music and Arts Film Festival, Seoul",
            "category": "Best Music Video — Freedom",
            "year": ""
          },
          {
            "award": "ZILANT International Film Festival",
            "category": "Best Music Video — Freedom",
            "year": ""
          },
          {
            "award": "Fajr Music Festival",
            "category": "Best Songwriting",
            "year": "2022"
          },
          {
            "award": "Baku Poetry Festival",
            "category": "Honorary Diploma",
            "year": "2015"
          }
        ],
        "priorWork": {
          "title": "CHESHMAT (2014)",
          "description": "Before Azadichords, Kamran composed and produced <em>CHESHMAT</em> for vocalist Mehrnoosh — a record that shaped a generation, and drew the attention that would eventually silence him. Its official video, published on the Avang Music YouTube channel, has been viewed roughly 20 million times.",
          "videoUrl": ""
        }
      }
    ],
    "releases": [
      {
        "slug": "requiem-for-the-eternal-names",
        "title": "Requiem for the Eternal Names",
        "catalogNumber": "AZC-001",
        "type": "album",
        "artist": "kamran-rasoolzadeh",
        "status": "upcoming",
        "releaseDate": "2027-01-08",
        "coverImageCaption": "Requiem for the Eternal Names — album art",
        "tagline": "The first release from Azadichords — out January 8, 2027.",
        "description": "Eight songs by Kamran Rasoolzadeh, written for those whose names are now spoken in their place. A requiem held between grief and the stubborn hope of the living — mourning without surrender, memory without silence. The album arrives on January 8, 2027, the opening day of the first Azadichords Festival.",
        "demoAudioUrl": "",
        "videoUrl": "",
        "videoCaption": "",
        "tracks": [
          {
            "trackNumber": 1,
            "title": "Darkness (1819)",
            "duration": "",
            "previewUrl": ""
          },
          {
            "trackNumber": 2,
            "title": "Iran-e Jan",
            "duration": "",
            "previewUrl": ""
          },
          {
            "trackNumber": 3,
            "title": "Still Alive",
            "duration": "",
            "previewUrl": ""
          },
          {
            "trackNumber": 4,
            "title": "Javidnam — The Eternal Name",
            "duration": "",
            "previewUrl": ""
          },
          {
            "trackNumber": 5,
            "title": "Khodash",
            "duration": "",
            "previewUrl": ""
          },
          {
            "trackNumber": 6,
            "title": "A Trail of Blood",
            "duration": "",
            "previewUrl": ""
          },
          {
            "trackNumber": 7,
            "title": "If I Die",
            "duration": "",
            "previewUrl": ""
          },
          {
            "trackNumber": 8,
            "title": "The Tree",
            "duration": "",
            "previewUrl": ""
          }
        ],
        "streamingLinks": [],
        "supportTierLink": true,
        "purchaseNote": "Streaming everywhere from January 8 — and available as a digital bundle with the poetry collection Sans Toi."
      }
    ],
    "activityPage": {
      "eyebrow": "Activity",
      "title": "Activity",
      "intro": "A running record of where Azadichords has been — performances, releases, and the milestones along the way.",
      "emptyStateNote": "Azadichords is early. This record starts with the first release and the first show — both are still ahead."
    },
    "activity": [],
    "press": {
      "eyebrow": "Press",
      "title": "Press",
      "paragraphs": [
        "Press materials and interviews will appear here as they're published.",
        "For press inquiries, use the contact form."
      ]
    },
    "services": {
      "eyebrow": "Services",
      "title": "What the Label Offers",
      "intro": "Beyond release, Azadichords works alongside the artists it houses at every stage a record needs before it reaches an audience.",
      "items": [
        {
          "title": "Production & Mixing",
          "description": "Studio time, arrangement, and audio engineering support, from first draft to final master."
        },
        {
          "title": "Distribution",
          "description": "Placing the work on every major platform, worldwide, under the artist's own name."
        },
        {
          "title": "Visual Identity",
          "description": "Album art, music videos, and the visual language that carries a record beyond its audio."
        },
        {
          "title": "Live Performance",
          "description": "From a first show to a touring itinerary — the logistics behind bringing a record to a stage."
        },
        {
          "title": "Licensing & Publishing",
          "description": "Protecting the work and placing it commercially, on terms the artist understands and agrees to."
        }
      ],
      "cta": {
        "label": "Working on something that belongs here? Get in Touch →",
        "href": "/contact"
      }
    },
    "submissions": {
      "eyebrow": "Submissions",
      "title": "For the Next Voice",
      "intro": "If your voice is something that can't stay silent, we want to hear it. Azadichords looks for artists whose music and poetry come from a belief, not just a genre. The main door is our festival: every entry is heard by the jury, and selected artists are invited to the label's annual compilation.",
      "guidelines": [
        "Festival entries — songs, music videos, compositions, vocal performances and poetry set to music — go through the festival page. Entry is free for the first edition.",
        "Outside the festival, you can still send 2–3 tracks in their current form, polished or not, with a few sentences about the story behind them.",
        "No press kit, no pitch deck. Just the music."
      ],
      "note": "Artists keep full ownership of their work. Every submission is listened to — even when we can't reply to each one.",
      "cta": {
        "label": "Submit to the Festival →",
        "href": "/festival"
      }
    },
    "support": {
      "eyebrow": "Support",
      "title": "Stand Behind the Voice",
      "intro": [
        "Azadichords is fully independent — no committee, no gatekeeper, no institutional funding. It exists because people choose to listen, share, and show up.",
        "There is no payment on this site. Each way to support below leads to the place where it actually happens."
      ],
      "ways": [
        {
          "name": "01",
          "title": "Own the Album",
          "description": "The memorial album together with the poetry collection Sans Toi — a digital bundle, sold directly by the artist's studio.",
          "cta": {
            "label": "Get the bundle →",
            "href": "https://www.youality.fr"
          }
        },
        {
          "name": "02",
          "title": "Listen and Share",
          "description": "From January 8, 2027, every release streams on all major platforms. A save, a share, a playlist add — each one carries the music further than any budget could.",
          "cta": {
            "label": "Go to the music →",
            "href": "/music"
          }
        },
        {
          "name": "03",
          "title": "Be in the Room",
          "description": "Join us on January 8–9, 2027 for the first Azadichords Festival — a live concert, the competition, and the awards night.",
          "cta": {
            "label": "The festival →",
            "href": "/festival"
          }
        },
        {
          "name": "04",
          "title": "Partner With Us",
          "description": "Venues, media, cultural organisations and patrons who want to help bring free voices to a stage — we would like to hear from you.",
          "cta": {
            "label": "Get in touch →",
            "href": "/contact"
          }
        }
      ],
      "transparency": "Azadichords never asks for payment on this site. Direct sales of the album are handled by the artist's studio."
    },
    "festival": {
      "eyebrow": "Festival · First Edition",
      "title": "Azadichords Festival 2027",
      "intro": [
        "Two days for music that carries memory and freedom. Open to artists from anywhere, in any language — a competition, a live concert, and an awards night.",
        "The festival is where the label listens. Selected artists are invited to the Azadichords annual compilation, released on every major platform."
      ],
      "datesTitle": "Key Dates",
      "dates": [
        {
          "date": "2026-10-19",
          "endDate": "",
          "label": "Submissions open",
          "highlight": false
        },
        {
          "date": "2026-11-02",
          "endDate": "",
          "label": "Jury announced",
          "highlight": false
        },
        {
          "date": "2026-12-06",
          "endDate": "",
          "label": "Submission deadline",
          "highlight": false
        },
        {
          "date": "2026-12-20",
          "endDate": "",
          "label": "Selections announced",
          "highlight": false
        },
        {
          "date": "2027-01-08",
          "endDate": "2027-01-09",
          "label": "The festival",
          "highlight": true
        }
      ],
      "categoriesTitle": "Competition Categories",
      "categories": [
        {
          "title": "Best Original Song",
          "description": "An original song, words and music, in any language."
        },
        {
          "title": "Best Music Video",
          "description": "The visual life of a song — live action, animation or archive."
        },
        {
          "title": "Best Instrumental or Composition",
          "description": "Music without words that still speaks."
        },
        {
          "title": "Best Vocal Performance",
          "description": "A voice heard on its own terms."
        },
        {
          "title": "Best Poetry Set to Music",
          "description": "Where a poem becomes a song — the root of Azadichords."
        }
      ],
      "entryTitle": "How to Enter",
      "entrySteps": [
        "Choose a category and prepare your work — a finished piece or a strong draft.",
        "Submit through the festival's FilmFreeway listing before December 6, 2026.",
        "Tick the compilation consent — a non-exclusive permission to include your work on the Azadichords compilation if it is selected. Ownership stays with you."
      ],
      "entryFee": "Entry is free for the first edition.",
      "programmeTitle": "Programme",
      "programme": [
        {
          "date": "2027-01-08",
          "title": "Opening Night — Live Concert",
          "description": "A curated concert of invited artists, and the release of the label's first album, Requiem for the Eternal Names."
        },
        {
          "date": "2027-01-09",
          "title": "Selections & Awards",
          "description": "Screenings and listening of the selected works, followed by the awards."
        }
      ],
      "juryTitle": "Jury",
      "juryText": "Musicians, poets and critics from the diaspora and beyond. The jury is announced on November 2, 2026.",
      "venueTitle": "Venue",
      "venueText": "Chantilly, near Paris, France — held alongside the YOUALITY International Film Festival. Exact venue to be announced.",
      "cta": {
        "label": "Get notified when submissions open →",
        "href": "/contact"
      },
      "ctaNote": "Submissions open on October 19, 2026.",
      "detailsLabel": "Full festival details →"
    },
    "contact": {
      "eyebrow": "Contact",
      "title": "Get in Touch",
      "subhead": "For music, festival, press, partnership or performance inquiries.",
      "fields": {
        "name": "Name",
        "email": "Email",
        "subject": "Subject",
        "category": "Category",
        "message": "Message"
      },
      "categories": [
        "General",
        "Festival",
        "Submission",
        "Press",
        "Booking",
        "Licensing",
        "Partnership"
      ],
      "submit": "Send",
      "sending": "Sending…",
      "successMessage": "Thanks — your message has been sent. We'll get back to you soon.",
      "errorMessage": "Something went wrong. Please try again, or email us directly at contact@azadichords.com."
    },
    "footer": {
      "copyright": "AZADICHORDS © 2026 — Paris · Label & Festival",
      "social": [
        {
          "label": "Instagram",
          "href": ""
        },
        {
          "label": "YouTube",
          "href": ""
        },
        {
          "label": "Spotify",
          "href": ""
        },
        {
          "label": "Telegram",
          "href": ""
        }
      ],
      "disclaimer": "Azadichords is an independent label and festival with no affiliation to any political party, movement, or government."
    }
  },
  "fa": {
    "nav": {
      "brand": "AZADICHORDS",
      "tagline": "خانه‌ی صداهای آزاد",
      "links": [
        {
          "href": "/manifesto",
          "label": "مانیفست"
        },
        {
          "href": "/music",
          "label": "موسیقی"
        },
        {
          "href": "/festival",
          "label": "جشنواره"
        },
        {
          "href": "/artists",
          "label": "هنرمندان"
        },
        {
          "href": "/submissions",
          "label": "ارسال اثر"
        },
        {
          "href": "/support",
          "label": "حمایت"
        },
        {
          "href": "/contact",
          "label": "تماس"
        }
      ]
    },
    "hero": {
      "eyebrow": "لیبل و جشنواره‌ی مستقل موسیقی — پاریس",
      "title": "AZADICHORDS",
      "subhead": "خانه‌ای برای صداهای آزاد — لیبلی که منتشرشان می‌کند، جشنواره‌ای که پیدایشان می‌کند.",
      "ctaPrimary": {
        "label": "بشنوید",
        "href": "/music"
      },
      "ctaSecondary": {
        "label": "جشنواره",
        "href": "/festival"
      },
      "scrollHint": "(برای ادامه اسکرول کنید)",
      "promoBar": {
        "label": "جشنواره‌ی آزادی‌کورد · ۸ و ۹ ژانویه ۲۰۲۷ · ارسالِ اثر رایگان",
        "href": "/festival"
      }
    },
    "manifesto": {
      "eyebrow": "مانیفست",
      "title": "لیبلی ساخته‌شده در تبعید",
      "imageCaption": "Azadichords — Requiem for the Eternal Names, album art",
      "paragraphs": [
        "آزادی‌کورد از دو کلمه ساخته شده: آزادی، و آکورد. اینجا این دو یکی می‌شن.",
        "ما یک لیبلِ مستقلیم برای صداهایی که نمی‌تونن، و نمی‌خوان، ساکت بمونن. برای شعر و موسیقی‌ای که از دلِ سانسور بیرون می‌زنه، نه با اجازه‌ی سانسور.",
        "ما هنرمند منتشر نمی‌کنیم؛ یک باور منتشر می‌کنیم: که صدای هر آدمی، حتی در تبعید، حتی در سکوتِ اجباری، حق داره شنیده بشه.",
        "این لیبل با یک صدا شروع شد. قرار نیست با همون یکی تموم بشه.",
        "آزادی‌کورد از یک تصمیم شروع شد: که موسیقی و شعرِ متعهد، لایقِ لیبلی‌ست که پشتش وایسه — نه فقط پشتِ یک آهنگ.",
        "هر آلبوم، هر ترک، هر شعر، قدمیه به‌سمتِ روزی که این لیبل خونه‌ی چند صدا باشه، نه یکی.",
        "برای همین این لیبل یک درِ دوم هم داره: یک جشنواره. هر سال صداهایی رو که هنوز شنیده نشدن کنارِ هم جمع می‌کنه، و لیبل صداهای برگزیده رو دورتر می‌بره."
      ],
      "closing": "کامران رسول‌زاده — شاعر، آهنگ‌ساز، و خواننده-ترانه‌سرا — این لیبل رو به‌عنوانِ اولین هنرمندش بنیان گذاشت؛ نه به این نیت که تنها بمونه، بلکه به این نیت که اولین صدا باشه از صداهای بیشتری که قراره بیان.",
      "cta": {
        "label": "هنرمند را بشناسید ←",
        "href": "/artists"
      }
    },
    "music": {
      "eyebrow": "موسیقی",
      "title": "موسیقی",
      "intro": "کاتالوگِ آزادی‌کورد با یک سوگنامه آغاز می‌شود — و با صداهایی که جشنواره‌مان به روشنایی می‌آورد ادامه پیدا می‌کند.",
      "closing": "انتشارِ بعدیِ لیبل: مجموعه‌ای از آثارِ هنرمندانِ برگزیده‌ی جشنواره‌ی آزادی‌کورد ۲۰۲۷.",
      "comingSoonLabel": "به‌زودی",
      "tracksComingSoonLabel": "ترک‌ها به‌زودی.",
      "videoComingSoonLabel": "نخستین موزیک‌ویدیو پیش از آلبوم منتشر می‌شود.",
      "demoComingSoonLabel": "نخستین شنیدن، به‌زودی.",
      "listenLabel": "بشنوید",
      "tracksLabel": "قطعه‌ها",
      "videoLabel": "ویدیو",
      "typeLabels": {
        "album": "آلبوم",
        "single": "تک‌آهنگ",
        "ep": "ای‌پی"
      },
      "getReleaseLabel": "تهیه‌ی این اثر",
      "getReleaseNote": "پس از انتشار همه‌جا بشنوید — یا مستقیم از هنرمند تهیه‌اش کنید.",
      "getReleaseCtaLabel": "ببینید چطور ←"
    },
    "artistsPage": {
      "eyebrow": "هنرمندان",
      "title": "هنرمندان",
      "intro": "هر هنرمندِ آزادی‌کورد، صداییه که تصمیم گرفته ساکت نمونه."
    },
    "artists": [
      {
        "slug": "kamran-rasoolzadeh",
        "name": "Kamran Rasoolzadeh",
        "role": "شاعر، آهنگساز، خواننده-ترانه‌سرا",
        "badge": "هنرمند بنیان‌گذار",
        "imageCaption": "portrait — Kamran, close crop",
        "intro": "کامران رسول‌زاده می‌نویسد، می‌سازد و می‌خواند؛ ترانه‌هایی شکل‌گرفته از تبعید و بازگشت. آثارش ممنوع و جایزه‌گرفته‌اند و او پس از سال‌ها سکوت، دوباره آغاز می‌کند.",
        "bio": "کامران رسول‌زاده شاعر، آهنگساز و خواننده-ترانه‌سرای ایرانی است. اشعارش برای بیش از یک دهه در صدر پرفروش‌ترین‌های ایران بوده‌اند. در سال ۲۰۱۴، او آلبوم «چشمت» را برای خواننده مهرنوش ساخت و تهیه کرد — آلبومی که با وجودِ محدودیت‌هایی که بر آن اعمال شد، و تا حدی به‌خاطرِ همان محدودیت‌ها، یکی از آثار ماندگارِ نسل خود شد. پس از سال‌ها سانسور و فشار مکرر از سوی مقامات، ایران را ترک کرد و در فرانسه ساکن شد، جایی که اکنون زندگی و کار می‌کند. او آزادی‌کورد را به‌عنوان هنرمند بنیان‌گذار پایه‌گذاری کرد.",
        "cta": {
          "label": "موسیقی را کاوش کنید ←",
          "href": "/music"
        },
        "recognition": [
          {
            "award": "Iranian Film Festival San Francisco",
            "category": "Best Music Video — Freedom",
            "year": "2022"
          },
          {
            "award": "K-Music and Arts Film Festival, Seoul",
            "category": "Best Music Video — Freedom",
            "year": ""
          },
          {
            "award": "ZILANT International Film Festival",
            "category": "Best Music Video — Freedom",
            "year": ""
          },
          {
            "award": "Fajr Music Festival",
            "category": "Best Songwriting",
            "year": "2022"
          },
          {
            "award": "Baku Poetry Festival",
            "category": "Honorary Diploma",
            "year": "2015"
          }
        ],
        "priorWork": {
          "title": "چشمت (۲۰۱۴)",
          "description": "پیش از آزادی‌کورد، کامران آلبوم «چشمت» را برای خواننده مهرنوش ساخت و تهیه کرد — اثری که نسلی را شکل داد و توجهی جلب کرد که سرانجام به سکوتش انجامید. ویدیوی رسمی آن، منتشرشده در کانال یوتیوب Avang Music، حدود ۲۰ میلیون بار دیده شده است.",
          "videoUrl": ""
        }
      }
    ],
    "releases": [
      {
        "slug": "requiem-for-the-eternal-names",
        "title": "سوگنامه‌ی جاویدنام‌ها",
        "catalogNumber": "AZC-001",
        "type": "album",
        "artist": "kamran-rasoolzadeh",
        "status": "upcoming",
        "releaseDate": "2027-01-08",
        "coverImageCaption": "Requiem for the Eternal Names — album art",
        "tagline": "نخستین انتشارِ آزادی‌کورد — ۸ ژانویه ۲۰۲۷.",
        "description": "هشت ترانه از کامران رسول‌زاده، برای کسانی که حالا نامشان به‌جای خودشان شنیده می‌شود. سوگنامه‌ای میانِ اندوه و امیدِ سرسختِ زندگان — سوگی بی‌تسلیم، یادی بی‌سکوت. آلبوم ۸ ژانویه ۲۰۲۷، روزِ گشایشِ نخستین جشنواره‌ی آزادی‌کورد، منتشر می‌شود.",
        "demoAudioUrl": "",
        "videoUrl": "",
        "videoCaption": "",
        "tracks": [
          {
            "trackNumber": 1,
            "title": "Darkness (۱۸۱۹)",
            "duration": "",
            "previewUrl": ""
          },
          {
            "trackNumber": 2,
            "title": "ایرانِ جان",
            "duration": "",
            "previewUrl": ""
          },
          {
            "trackNumber": 3,
            "title": "هنوز زنده‌ایم",
            "duration": "",
            "previewUrl": ""
          },
          {
            "trackNumber": 4,
            "title": "جاویدنام",
            "duration": "",
            "previewUrl": ""
          },
          {
            "trackNumber": 5,
            "title": "خودش",
            "duration": "",
            "previewUrl": ""
          },
          {
            "trackNumber": 6,
            "title": "ردِ خون",
            "duration": "",
            "previewUrl": ""
          },
          {
            "trackNumber": 7,
            "title": "اگه مردم",
            "duration": "",
            "previewUrl": ""
          },
          {
            "trackNumber": 8,
            "title": "درخت",
            "duration": "",
            "previewUrl": ""
          }
        ],
        "streamingLinks": [],
        "supportTierLink": true,
        "purchaseNote": "از ۸ ژانویه روی همه‌ی پلتفرم‌ها — و همچنین به‌صورتِ بسته‌ی دیجیتال همراه با مجموعه‌شعرِ «بی‌تو»."
      }
    ],
    "activityPage": {
      "eyebrow": "فعالیت‌ها",
      "title": "فعالیت‌ها",
      "intro": "روایتی از مسیرِ آزادی‌کورد — اجراها، ریلیزها، و نقاطِ عطفِ این راه.",
      "emptyStateNote": "آزادی‌کورد هنوز در ابتداست. این روایت با اولین ریلیز و اولین اجرا شروع می‌شه — که هر دو هنوز پیشِ رو هستن."
    },
    "activity": [],
    "press": {
      "eyebrow": "مطبوعات",
      "title": "مطبوعات",
      "paragraphs": [
        "مطالبِ مطبوعاتی و مصاحبه‌ها همین‌جا و به‌محضِ انتشار قرار می‌گیرن.",
        "برای درخواست‌های مطبوعاتی از فرمِ تماس استفاده کنید."
      ]
    },
    "services": {
      "eyebrow": "خدمات",
      "title": "آنچه لیبل ارائه می‌دهد",
      "intro": "فراتر از انتشار، آزادی‌کورد در تمامِ مراحلی که یک اثر پیش از رسیدن به مخاطب طی می‌کنه، کنارِ هنرمندانش می‌ایسته.",
      "items": [
        {
          "title": "تولید و میکس",
          "description": "زمانِ استودیو، تنظیم، و پشتیبانیِ مهندسیِ صدا، از اولین پیش‌نویس تا مسترِ نهایی."
        },
        {
          "title": "توزیع",
          "description": "قرار دادنِ اثر روی تمامِ پلتفرم‌های اصلی، در سراسرِ دنیا، زیرِ نامِ خودِ هنرمند."
        },
        {
          "title": "هویت بصری",
          "description": "طراحیِ کاورِ آلبوم، موزیک‌ویدیو، و زبانِ بصری‌ای که اثر را فراتر از صدایش می‌برد."
        },
        {
          "title": "اجرای زنده",
          "description": "از اولین اجرا تا برنامه‌ی یک تور — تمامِ لجستیکِ رسوندنِ یک اثر به روی صحنه."
        },
        {
          "title": "لایسنس و نشر",
          "description": "محافظت از اثر و قرار دادنِ آن در بازار، با شرایطی که هنرمند می‌فهمد و باهاش موافقه."
        }
      ],
      "cta": {
        "label": "کاری داری که اینجا جاش هست؟ تماس بگیر ←",
        "href": "/contact"
      }
    },
    "submissions": {
      "eyebrow": "ارسال اثر",
      "title": "برای صدای بعدی",
      "intro": "اگر صدایتان چیزی است که نمی‌تواند ساکت بماند، می‌خواهیم آن را بشنویم. آزادی‌کورد به‌دنبالِ هنرمندانی است که موسیقی و شعرشان از یک باور می‌آید، نه فقط از یک ژانر. درِ اصلی، جشنواره‌ی ماست: همه‌ی آثار را هیئت داوران می‌شنود و هنرمندانِ برگزیده به آلبومِ مجموعه‌ی سالانه‌ی لیبل دعوت می‌شوند.",
      "guidelines": [
        "آثارِ جشنواره — ترانه، موزیک‌ویدیو، آهنگسازی، اجرای آوازی و شعرِ همراه با موسیقی — از طریقِ صفحه‌ی جشنواره ارسال می‌شوند. ارسال در دوره‌ی نخست رایگان است.",
        "خارج از جشنواره هم می‌توانید ۲ تا ۳ قطعه را، به همان شکلی که هست، همراه با چند جمله درباره‌ی داستانِ پشتِ آن‌ها بفرستید.",
        "نه پرس‌کیت، نه پیچ‌دک. فقط موسیقی."
      ],
      "note": "مالکیتِ اثر به‌طورِ کامل نزدِ هنرمند می‌ماند. به همه‌ی آثار گوش داده می‌شود — حتی وقتی نتوانیم به تک‌تکشان پاسخ دهیم.",
      "cta": {
        "label": "ارسال اثر به جشنواره ←",
        "href": "/festival"
      }
    },
    "support": {
      "eyebrow": "حمایت",
      "title": "پشتِ این صدا بایستید",
      "intro": [
        "آزادی‌کورد کاملاً مستقل است — بی‌کمیته، بی‌دروازه‌بان، بی‌بودجه‌ی نهادی. این لیبل زنده است چون آدم‌ها تصمیم می‌گیرند گوش بدهند، به اشتراک بگذارند، و حاضر باشند.",
        "روی این سایت هیچ پرداختی انجام نمی‌شود. هر راهِ حمایتی که در ادامه می‌بینید، شما را به جایی می‌برد که آن حمایت واقعاً اتفاق می‌افتد."
      ],
      "ways": [
        {
          "name": "01",
          "title": "آلبوم را داشته باشید",
          "description": "آلبومِ سوگنامه همراه با مجموعه‌شعرِ «بی‌تو» — یک بسته‌ی دیجیتال، مستقیم از استودیوی هنرمند.",
          "cta": {
            "label": "تهیه‌ی بسته ←",
            "href": "https://www.youality.fr"
          }
        },
        {
          "name": "02",
          "title": "بشنوید و به اشتراک بگذارید",
          "description": "از ۸ ژانویه ۲۰۲۷، همه‌ی انتشارها روی تمامِ پلتفرم‌های اصلی در دسترس است. هر ذخیره، هر اشتراک‌گذاری، هر افزودن به پلی‌لیست — این موسیقی را دورتر از هر بودجه‌ای می‌برد.",
          "cta": {
            "label": "رفتن به موسیقی ←",
            "href": "/music"
          }
        },
        {
          "name": "03",
          "title": "در سالن باشید",
          "description": "۸ و ۹ ژانویه ۲۰۲۷ در نخستین جشنواره‌ی آزادی‌کورد کنارِ ما باشید — کنسرتِ زنده، بخشِ رقابتی و شبِ اهدای جوایز.",
          "cta": {
            "label": "جشنواره ←",
            "href": "/festival"
          }
        },
        {
          "name": "04",
          "title": "همراهِ ما شوید",
          "description": "سالن‌ها، رسانه‌ها، نهادهای فرهنگی و حامیانی که می‌خواهند صداهای آزاد را به صحنه برسانند — مشتاقیم از شما بشنویم.",
          "cta": {
            "label": "تماس بگیرید ←",
            "href": "/contact"
          }
        }
      ],
      "transparency": "آزادی‌کورد روی این سایت هرگز درخواستِ پرداخت نمی‌کند. فروشِ مستقیمِ آلبوم از طریقِ استودیوی هنرمند انجام می‌شود."
    },
    "festival": {
      "eyebrow": "جشنواره · دوره‌ی نخست",
      "title": "جشنواره‌ی آزادی‌کورد ۲۰۲۷",
      "intro": [
        "دو روز برای موسیقی‌ای که یاد و آزادی را با خود دارد. باز برای هنرمندانی از هر جای جهان و به هر زبانی — بخشِ رقابتی، کنسرتِ زنده، و شبِ اهدای جوایز.",
        "جشنواره جایی است که لیبل گوش می‌دهد. هنرمندانِ برگزیده به آلبومِ مجموعه‌ی سالانه‌ی آزادی‌کورد دعوت می‌شوند که روی همه‌ی پلتفرم‌های اصلی منتشر می‌شود."
      ],
      "datesTitle": "تاریخ‌های کلیدی",
      "dates": [
        {
          "date": "2026-10-19",
          "endDate": "",
          "label": "آغازِ ارسالِ اثر",
          "highlight": false
        },
        {
          "date": "2026-11-02",
          "endDate": "",
          "label": "معرفیِ هیئت داوران",
          "highlight": false
        },
        {
          "date": "2026-12-06",
          "endDate": "",
          "label": "پایانِ مهلتِ ارسال",
          "highlight": false
        },
        {
          "date": "2026-12-20",
          "endDate": "",
          "label": "اعلامِ آثارِ برگزیده",
          "highlight": false
        },
        {
          "date": "2027-01-08",
          "endDate": "2027-01-09",
          "label": "برگزاریِ جشنواره",
          "highlight": true
        }
      ],
      "categoriesTitle": "بخش‌های رقابتی",
      "categories": [
        {
          "title": "بهترین ترانه‌ی اورجینال",
          "description": "ترانه‌ای اورجینال، کلام و موسیقی، به هر زبانی."
        },
        {
          "title": "بهترین موزیک‌ویدیو",
          "description": "زندگیِ تصویریِ یک ترانه — فیلم، انیمیشن یا آرشیو."
        },
        {
          "title": "بهترین قطعه‌ی بی‌کلام یا آهنگسازی",
          "description": "موسیقیِ بی‌کلامی که همچنان حرف می‌زند."
        },
        {
          "title": "بهترین اجرای آوازی",
          "description": "صدایی که به شیوه‌ی خودش شنیده می‌شود."
        },
        {
          "title": "بهترین شعر همراه با موسیقی",
          "description": "جایی که شعر ترانه می‌شود — ریشه‌ی آزادی‌کورد."
        }
      ],
      "entryTitle": "شیوه‌ی شرکت",
      "entrySteps": [
        "یک بخش را انتخاب کنید و اثرتان را آماده کنید — اثرِ نهایی یا پیش‌نویسی قوی.",
        "اثر را تا ۶ دسامبر ۲۰۲۶ از طریقِ صفحه‌ی جشنواره در FilmFreeway ارسال کنید.",
        "رضایتِ حضور در آلبومِ مجموعه را تأیید کنید — اجازه‌ای غیرانحصاری برای قرار گرفتنِ اثرتان در آلبومِ آزادی‌کورد در صورتِ برگزیده شدن. مالکیتِ اثر نزدِ شما می‌ماند."
      ],
      "entryFee": "ارسالِ اثر در دوره‌ی نخست رایگان است.",
      "programmeTitle": "برنامه",
      "programme": [
        {
          "date": "2027-01-08",
          "title": "شبِ افتتاح — کنسرتِ زنده",
          "description": "کنسرتی کیوریت‌شده با هنرمندانِ دعوت‌شده، و انتشارِ نخستین آلبومِ لیبل، «سوگنامه‌ی جاویدنام‌ها»."
        },
        {
          "date": "2027-01-09",
          "title": "آثارِ برگزیده و اهدای جوایز",
          "description": "نمایش و شنیدنِ آثارِ برگزیده، و سپس اهدای جوایز."
        }
      ],
      "juryTitle": "هیئت داوران",
      "juryText": "موسیقی‌دانان، شاعران و منتقدانی از دیاسپورا و فراتر از آن. اعضای هیئت داوران ۲ نوامبر ۲۰۲۶ معرفی می‌شوند.",
      "venueTitle": "محل برگزاری",
      "venueText": "شانتیی، نزدیکِ پاریس، فرانسه — هم‌زمان با جشنواره‌ی بین‌المللی فیلم YOUALITY. محلِ دقیق به‌زودی اعلام می‌شود.",
      "cta": {
        "label": "خبرم کنید وقتی ارسال آغاز شد ←",
        "href": "/contact"
      },
      "ctaNote": "ارسالِ اثر از ۱۹ اکتبر ۲۰۲۶ آغاز می‌شود.",
      "detailsLabel": "جزئیاتِ کاملِ جشنواره ←"
    },
    "contact": {
      "eyebrow": "تماس",
      "title": "با ما در تماس باشید",
      "subhead": "برای پرسش‌های مربوط به موسیقی، جشنواره، رسانه، همکاری یا اجرا.",
      "fields": {
        "name": "نام",
        "email": "ایمیل",
        "subject": "موضوع",
        "category": "دسته",
        "message": "پیام"
      },
      "categories": [
        "عمومی",
        "جشنواره",
        "ارسال اثر",
        "مطبوعات",
        "رزرو اجرا",
        "لایسنس",
        "همکاری"
      ],
      "submit": "ارسال",
      "sending": "در حال ارسال…",
      "successMessage": "سپاس — پیامتان ارسال شد. به‌زودی با شما تماس می‌گیریم.",
      "errorMessage": "مشکلی پیش آمد. لطفاً دوباره تلاش کنید، یا مستقیم به contact@azadichords.com ایمیل بزنید."
    },
    "footer": {
      "copyright": "AZADICHORDS © 2026 — Paris · Label & Festival",
      "social": [
        {
          "label": "Instagram",
          "href": ""
        },
        {
          "label": "YouTube",
          "href": ""
        },
        {
          "label": "Spotify",
          "href": ""
        },
        {
          "label": "Telegram",
          "href": ""
        }
      ],
      "disclaimer": "آزادی‌کورد لیبل و جشنواره‌ای مستقل است و به هیچ حزب، جنبش یا دولتی وابسته نیست."
    }
  }
};
