// Regenerates src/lib/content.ts from the editable files in content/
// (pages/*.yml, artists/*.md, albums/*.md). Runs automatically before
// `next dev` and `next build` (see package.json), so anything committed
// through the CMS is picked up on the next run/deploy with no manual step.
//
// Do not hand-edit src/lib/content.ts — edit the files in content/ instead.

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { load as loadYaml } from "js-yaml";
import matter from "gray-matter";

const root = path.dirname(fileURLToPath(import.meta.url));
const contentDir = path.join(root, "..", "content");
const outFile = path.join(root, "..", "src", "lib", "content.ts");

function readYaml(name) {
  const file = path.join(contentDir, "pages", `${name}.yml`);
  return loadYaml(readFileSync(file, "utf8"));
}

function readFolder(folder) {
  const dir = path.join(contentDir, folder);
  return readdirSync(dir)
    .filter((f) => f.endsWith(".md"))
    .sort()
    .map((f) => {
      const { data, content: body } = matter(readFileSync(path.join(dir, f), "utf8"));
      return { ...data, body: body.trim() };
    });
}

const nav = readYaml("nav");
const home = readYaml("home");
const manifesto = readYaml("manifesto");
const music = readYaml("music");
const artistsPage = readYaml("artists-page");
const press = readYaml("press");
const support = readYaml("support");
const contact = readYaml("contact");
const footer = readYaml("footer");

const artists = readFolder("artists").map((a) => ({
  slug: a.slug,
  name: a.name,
  role: a.role,
  imageCaption: a.imageCaption,
  intro: a.intro,
  bio: a.body,
  cta: { label: a.ctaLabel, href: a.ctaHref },
}));

const albums = readFolder("albums").map((a) => ({
  slug: a.slug,
  title: a.title,
  artist: a.artist,
  year: a.year,
  status: a.status,
  coverImageCaption: a.coverImageCaption,
  blurb: a.body,
  tracks: a.tracks ?? [],
  musicVideoUrl: a.musicVideoUrl || "",
  musicVideoCaption: a.musicVideoCaption || "",
  externalListen: { label: a.externalListenLabel, href: a.externalListenHref },
}));

const content = {
  nav: {
    brand: nav.brand,
    links: nav.links,
  },
  hero: {
    eyebrow: home.eyebrow,
    title: home.title,
    subhead: home.subhead,
    ctaPrimary: { label: home.ctaPrimaryLabel, href: home.ctaPrimaryHref },
    ctaSecondary: { label: home.ctaSecondaryLabel, href: home.ctaSecondaryHref },
    scrollHint: home.scrollHint,
  },
  manifesto: {
    eyebrow: manifesto.eyebrow,
    title: manifesto.title,
    imageCaption: manifesto.imageCaption,
    paragraphs: manifesto.paragraphs,
    closing: manifesto.closing,
    cta: { label: manifesto.ctaLabel, href: manifesto.ctaHref },
  },
  music: {
    eyebrow: music.eyebrow,
    title: music.title,
    intro: music.intro,
    closing: music.closing,
    comingSoonLabel: music.comingSoonLabel,
    tracksComingSoonLabel: music.tracksComingSoonLabel,
    videoComingSoonLabel: music.videoComingSoonLabel,
  },
  artistsPage: {
    eyebrow: artistsPage.eyebrow,
    title: artistsPage.title,
    intro: artistsPage.intro,
  },
  artists,
  albums,
  press: {
    eyebrow: press.eyebrow,
    title: press.title,
    paragraphs: press.paragraphs,
  },
  support: {
    eyebrow: support.eyebrow,
    title: support.title,
    intro: support.intro,
    tiers: support.tiers,
    cta: { label: support.ctaLabel, href: support.ctaHref },
    transparency: support.transparency,
  },
  contact: {
    eyebrow: contact.eyebrow,
    title: contact.title,
    subhead: contact.subhead,
    fields: {
      name: contact.fieldNameLabel,
      email: contact.fieldEmailLabel,
      subject: contact.fieldSubjectLabel,
      category: contact.fieldCategoryLabel,
    },
    categories: contact.categories,
    submit: contact.submitLabel,
  },
  footer: {
    copyright: footer.copyright,
    social: footer.social,
    disclaimer: footer.disclaimer,
  },
};

const banner = `// AUTO-GENERATED by scripts/generate-content.mjs — do not edit by hand.
// Edit the files in content/ instead (or use the CMS at /admin), then
// re-run \`npm run generate-content\` (also runs automatically before
// dev/build).

import type { Content } from "./content.types";

`;

writeFileSync(
  outFile,
  banner + `export const content: Content = ${JSON.stringify(content, null, 2)};\n`,
);

console.log(`Generated ${path.relative(process.cwd(), outFile)}`);
